#!/usr/bin/bash

set ${SET_X:+-x} -eou pipefail

trap '[[ $BASH_COMMAND != echo* ]] && [[ $BASH_COMMAND != log* ]] && echo "+ $BASH_COMMAND"' DEBUG

log() {
  echo "=== $* ==="
}

log "Installing RPM packages"

log "Install layered applications"

# Layered Applications
LAYERED_PACKAGES=(
    # Miracle WM Core
    aajohan-comfortaa-fonts
    abattis-cantarell-fonts
    abattis-cantarell-vf-fonts
    abrt
    abrt-addon-ccpp
    abrt-addon-kerneloops
    abrt-addon-pstoreoops
    abrt-addon-vmcore
    abrt-addon-xorg
    abrt-cli
    abrt-dbus
    abrt-desktop
    abrt-gui
    abrt-gui-libs
    abrt-libs
    abrt-plugin-bodhi
    abrt-tui
    acl
    adobe-mappings-cmap
    adobe-mappings-cmap-deprecated
    adobe-mappings-pdf
    adwaita-cursor-theme
    adwaita-icon-theme
    adwaita-icon-theme-legacy
    adwaita-mono-fonts
    adwaita-sans-fonts
    alsa-lib
    alsa-sof-firmware
    alsa-ucm
    alsa-utils
    alternatives
    amd-gpu-firmware
    amd-ucode-firmware
    anaconda
    anaconda-core
    anaconda-gui
    anaconda-install-env-deps
    anaconda-live
    anaconda-tui
    anaconda-widgets
    anthy-unicode
    antiword
    appstream
    appstream-data
    aribb24
    at
    atheros-firmware
    atk
    atkmm
    at-spi2-atk
    at-spi2-core
    attr
    audit
    audit-libs
    audit-rules
    augeas-libs
    authselect
    authselect-libs
    avahi
    avahi-glib
    avahi-gobject
    avahi-libs
    avahi-tools
    avif-pixbuf-loader
    b43-fwcutter
    b43-openfwwf
    basesystem
    bash
    bash-color-prompt
    bash-completion
    bc
    bind-libs
    bind-utils
    binutils
    blivet-data
    blivet-gui-runtime
    blueman
    bluez
    bluez-cups
    bluez-libs
    bluez-obexd
    bolt
    boost-atomic
    boost-filesystem
    boost-iostreams
    boost-program-options
    boost-regex
    boost-system
    braille-printer-app
    brcmfmac-firmware
    brightnessctl
    btrfs-progs
    bubblewrap
    bzip2
    bzip2-libs
    ca-certificates
    cairo
    cairo-gobject
    cairomm
    cairomm1.16
    c-ares
    cdparanoia-libs
    celluloid
    checkpolicy
    chrony
    cifs-utils
    cifs-utils-info
    cirrus-audio-firmware
    cjson
    cldr-emoji-annotation
    cldr-emoji-annotation-dtd
    codec2
    colord
    colord-libs
    color-filesystem
    compat-lua-libs
    composefs-libs
    compsize
    coreutils
    coreutils-common
    cpio
    cpp
    cpuinfo
    cracklib
    cracklib-dicts
    cronie
    cronie-anacron
    crontabs
    crypto-policies
    crypto-policies-scripts
    cryptsetup
    cryptsetup-libs
    ctags
    cups
    cups-browsed
    cups-client
    cups-filesystem
    cups-filters
    cups-filters-driverless
    cups-ipptool
    cups-libs
    cups-pk-helper
    curl
    cxl-libs
    cyrus-sasl-gssapi
    cyrus-sasl-lib
    cyrus-sasl-plain
    daxctl-libs
    dbus
    dbus-broker
    dbus-common
    dbus-daemon
    dbus-libs
    dbus-tools
    dbus-x11
    dconf
    default-editor
    default-fonts-am
    default-fonts-ar
    default-fonts-as
    default-fonts-ast
    default-fonts-be
    default-fonts-bg
    default-fonts-bn
    default-fonts-bo
    default-fonts-br
    default-fonts-chr
    default-fonts-cjk-mono
    default-fonts-cjk-sans
    default-fonts-cjk-serif
    default-fonts-core-emoji
    default-fonts-core-math
    default-fonts-core-mono
    default-fonts-core-sans
    default-fonts-core-serif
    default-fonts-dv
    default-fonts-dz
    default-fonts-el
    default-fonts-eo
    default-fonts-eu
    default-fonts-fa
    default-fonts-got
    default-fonts-gu
    default-fonts-he
    default-fonts-hi
    default-fonts-hy
    default-fonts-ia
    default-fonts-iu
    default-fonts-ka
    default-fonts-kab
    default-fonts-km
    default-fonts-kn
    default-fonts-ku
    default-fonts-lo
    default-fonts-mai
    default-fonts-ml
    default-fonts-mni
    default-fonts-mr
    default-fonts-my
    default-fonts-nb
    default-fonts-ne
    default-fonts-nn
    default-fonts-nqo
    default-fonts-nr
    default-fonts-nso
    default-fonts-or
    default-fonts-other-mono
    default-fonts-other-sans
    default-fonts-other-serif
    default-fonts-pa
    default-fonts-ru
    default-fonts-sat
    default-fonts-si
    default-fonts-ss
    default-fonts-syr
    default-fonts-ta
    default-fonts-te
    default-fonts-th
    default-fonts-tn
    default-fonts-ts
    default-fonts-uk
    default-fonts-ur
    default-fonts-ve
    default-fonts-vi
    default-fonts-xh
    default-fonts-yi
    default-fonts-zu
    deltarpm
    desktop-backgrounds-compat
    desktop-file-utils
    device-mapper
    device-mapper-event
    device-mapper-event-libs
    device-mapper-libs
    device-mapper-persistent-data
    dhcp-client
    dhcp-common
    diffutils
    dmidecode
    dnf5
    dnf5-plugins
    dnf-data
    dnf-plugins-core
    dnsmasq
    dos2unix
    dosfstools
    dotconf
    double-conversion
    dracut
    dracut-config-rescue
    dracut-live
    dracut-network
    dracut-squash
    duktape
    dunst
    e2fsprogs
    e2fsprogs-libs
    ed
    efibootmgr
    efi-filesystem
    efivar-libs
    egl-wayland
    elfutils
    elfutils-debuginfod-client
    elfutils-default-yama-scope
    elfutils-libelf
    elfutils-libs
    emacs-filesystem
    enchant2
    espeak-ng
    ethtool
    exempi
    exfatprogs
    exiv2
    exiv2-libs
    exo
    expat
    f2fs-tools
    f42-backgrounds-base
    fcft
    fdk-aac-free
    fedora-bookmarks
    fedora-gpg-keys
    fedora-logos
    fedora-release-common
    fedora-release-identity-miraclewm
    fedora-release-miraclewm
    fedora-repos
    ffmpeg-free
    fftw-libs-double
    fftw-libs-single
    file
    file-libs
    filesystem
    findutils
    firewalld
    firewalld-filesystem
    flac-libs
    flashrom
    flatpak-libs
    flite
    fmt
    fontconfig
    fonts-filesystem
    foot
    fpaste
    fprintd
    fprintd-pam
    freeglut
    freeimage
    freetype
    fribidi
    fstrm
    fuse
    fuse3
    fuse3-libs
    fuse-common
    fwupd
    fwupd-efi
    fwupd-plugin-flashrom
    fwupd-plugin-modem-manager
    fwupd-plugin-uefi-capsule-data
    game-music-emu
    garcon
    gawk
    gawk-all-langpacks
    gcr3
    gcr3-base
    gcr-libs
    gd
    gdb
    gdb-headless
    gdbm
    gdbm-libs
    gdk-pixbuf2
    gdk-pixbuf2-modules
    gdouros-symbola-fonts
    geoclue2
    geolite2-city
    geolite2-country
    gettext-envsubst
    gettext-libs
    gettext-runtime
    ghostscript
    ghostscript-tools-fonts
    ghostscript-tools-printing
    giflib
    glib2
    glibc
    glibc-all-langpacks
    glibc-common
    glibc-gconv-extra
    glibmm2.4
    glibmm2.68
    glib-networking
    glx-utils
    gmp
    gnome-abrt
    gnome-boxes
    gnome-disk-utility
    gnome-keyring
    gnome-keyring-pam
    gnome-themes-extra
    gnome-tweaks
    gnupg2
    gnupg2-smime
    gnutls
    gnutls-dane
    gobject-introspection
    google-droid-sans-fonts
    google-noto-color-emoji-fonts
    google-noto-fonts-common
    google-noto-naskh-arabic-vf-fonts
    google-noto-sans-arabic-vf-fonts
    google-noto-sans-armenian-vf-fonts
    google-noto-sans-bengali-vf-fonts
    google-noto-sans-canadian-aboriginal-vf-fonts
    google-noto-sans-cherokee-vf-fonts
    google-noto-sans-cjk-vf-fonts
    google-noto-sans-devanagari-vf-fonts
    google-noto-sans-ethiopic-vf-fonts
    google-noto-sans-georgian-vf-fonts
    google-noto-sans-gothic-fonts
    google-noto-sans-gujarati-vf-fonts
    google-noto-sans-gurmukhi-vf-fonts
    google-noto-sans-hebrew-vf-fonts
    google-noto-sans-kannada-vf-fonts
    google-noto-sans-khmer-vf-fonts
    google-noto-sans-lao-vf-fonts
    google-noto-sans-math-fonts
    google-noto-sans-meetei-mayek-vf-fonts
    google-noto-sans-mono-cjk-vf-fonts
    google-noto-sans-mono-vf-fonts
    google-noto-sans-nko-fonts
    google-noto-sans-ol-chiki-vf-fonts
    google-noto-sans-oriya-vf-fonts
    google-noto-sans-sinhala-vf-fonts
    google-noto-sans-symbols-2-fonts
    google-noto-sans-symbols-vf-fonts
    google-noto-sans-syriac-vf-fonts
    google-noto-sans-tamil-vf-fonts
    google-noto-sans-telugu-vf-fonts
    google-noto-sans-thaana-vf-fonts
    google-noto-sans-thai-vf-fonts
    google-noto-sans-vf-fonts
    google-noto-serif-armenian-vf-fonts
    google-noto-serif-bengali-vf-fonts
    google-noto-serif-cjk-vf-fonts
    google-noto-serif-devanagari-vf-fonts
    google-noto-serif-ethiopic-vf-fonts
    google-noto-serif-georgian-vf-fonts
    google-noto-serif-gujarati-vf-fonts
    google-noto-serif-gurmukhi-vf-fonts
    google-noto-serif-hebrew-vf-fonts
    google-noto-serif-kannada-vf-fonts
    google-noto-serif-khmer-vf-fonts
    google-noto-serif-lao-vf-fonts
    google-noto-serif-oriya-vf-fonts
    google-noto-serif-sinhala-vf-fonts
    google-noto-serif-tamil-vf-fonts
    google-noto-serif-telugu-vf-fonts
    google-noto-serif-thai-vf-fonts
    google-noto-serif-vf-fonts
    gpgme
    gpgmepp
    granite
    graphene
    graphite2
    graphviz-libs
    grep
    grim
    groff-base
    grub2-common
    grub2-efi-ia32
    grub2-efi-ia32-cdboot
    grub2-efi-x64
    grub2-efi-x64-cdboot
    grub2-efi-x64-modules
    grub2-pc
    grub2-pc-modules
    grub2-tools
    grub2-tools-efi
    grub2-tools-extra
    grub2-tools-minimal
    grubby
    gsettings-desktop-schemas
    gsm
    gssdp
    gssproxy
    gstreamer1
    gstreamer1-plugin-dav1d
    gstreamer1-plugin-libav
    gstreamer1-plugin-openh264
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-bad-free-libs
    gstreamer1-plugins-base
    gstreamer1-plugins-good
    gstreamer1-plugins-good-qt6
    gstreamer1-plugins-ugly-free
    gtk3
    gtk3-immodule-xim
    gtk4
    gtk-layer-shell
    gtkmm3.0
    gtkmm4.0
    gtk-update-icon-cache
    guestmount
    gupnp
    gupnp-igd
    gutenprint
    gutenprint-cups
    gutenprint-libs
    gvfs
    gvfs-afp
    gvfs-archive
    gvfs-client
    gvfs-fuse
    gvfs-gphoto2
    gvfs-mtp
    gvfs-nfs
    gvfs-smb
    gzip
    harfbuzz
    harfbuzz-icu
    hfsplus-tools
    hicolor-icon-theme
    hidapi
    highcontrast-icon-theme
    highway
    hiredis
    hostname
    hplip
    hplip-common
    hplip-libs
    hunspell
    hunspell-en
    hunspell-en-GB
    hunspell-en-US
    hunspell-filesystem
    hwdata
    hyperv-daemons
    hyperv-daemons-license
    hypervfcopyd
    hypervkvpd
    hypervvssd
    hyphen
    ibus
    ibus-anthy
    ibus-anthy-python
    ibus-chewing
    ibus-gtk3
    ibus-gtk4
    ibus-hangul
    ibus-libpinyin
    ibus-libs
    ibus-m17n
    ibus-setup
    ibus-table
    ibus-table-chinese
    ibus-table-chinese-cangjie
    ibus-typing-booster
    ilbc
    ima-evm-utils-libs
    ImageMagick
    ImageMagick-libs
    imath
    im-chooser
    im-chooser-common
    im-chooser-xfce
    imsettings
    imsettings-gsettings
    imsettings-libs
    imv
    inih
    inih-cpp
    iniparser
    initial-setup
    initial-setup-gui
    initial-setup-gui-wayland-miraclewm
    initscripts-service
    intel-audio-firmware
    intel-gmmlib
    intel-gpu-firmware
    intel-mediasdk
    intel-vpl-gpu-rt
    intel-vsc-firmware
    ipcalc
    iperf3
    ipp-usb
    iproute
    ipset
    ipset-libs
    iptables-libs
    iptables-nft
    iptstate
    iputils
    irqbalance
    iscsi-initiator-utils
    iscsi-initiator-utils-iscsiuio
    isns-utils-libs
    iso-codes
    isomd5sum
    iw
    iwlegacy-firmware
    iwlwifi-dvm-firmware
    iwlwifi-mvm-firmware
    jansson
    jasper-libs
    javascriptcoregtk4.1
    jbig2dec-libs
    jbigkit-libs
    jemalloc
    jomolhari-fonts
    jq
    json-c
    json-glib
    jxl-pixbuf-loader
    jxrlib
    kanshi
    kasumi-common
    kasumi-unicode
    kbd
    kbd-legacy
    kbd-misc
    kde-filesystem
    kdump-anaconda-addon
    kdump-utils
    kernel
    kernel-core
    kernel-modules
    kernel-modules-core
    kernel-modules-extra
    kexec-tools
    keyutils
    keyutils-libs
    kf6-filesystem
    kf6-karchive
    kf6-kimageformats
    kf6-kwindowsystem
    kmod
    kmod-libs
    konsole
    konsole-part
    kpartx
    krb5-libs
    kvantum
    kyotocabinet-libs
    lame-libs
    langtable
    layer-shell-qt
    lcms2
    ldns
    leptonica
    less
    liba52
    libacl
    libadwaita
    libaio
    libao
    libaom
    libappindicator-gtk3
    libarchive
    libaribcaption
    libass
    libassuan
    libasyncns
    libatasmart
    libatomic
    libattr
    libavc1394
    libavcodec-free
    libavdevice-free
    libavfilter-free
    libavformat-free
    libavif
    libavutil-free
    libb2
    libbabeltrace
    libbasicobjects
    libblkid
    libblockdev
    libblockdev-btrfs
    libblockdev-crypto
    libblockdev-dm
    libblockdev-fs
    libblockdev-loop
    libblockdev-lvm
    libblockdev-lvm-dbus
    libblockdev-mdraid
    libblockdev-mpath
    libblockdev-nvdimm
    libblockdev-nvme
    libblockdev-part
    libblockdev-plugins-all
    libblockdev-smart
    libblockdev-smartmontools
    libblockdev-swap
    libblockdev-tools
    libblockdev-utils
    libbluray
    libbpf
    libbrotli
    libbs2b
    libbytesize
    libcaca
    libcamera
    libcamera-ipa
    libcanberra
    libcanberra-gtk3
    libcap
    libcap-ng
    libcap-ng-python3
    libcbor
    libcdio
    libcdio-paranoia
    libchewing
    libchromaprint
    libcloudproviders
    libcollection
    libcom_err
    libcomps
    libcue
    libcupsfilters
    libcurl
    libdaemon
    libdatrie
    libdav1d
    libdbusmenu
    libdbusmenu-gtk3
    libdc1394
    libdecor
    libdeflate
    libdhash
    libdisplay-info
    libdnf
    libdnf5
    libdnf5-cli
    libdovi
    libdrm
    libdvdnav
    libdvdread
    libebur128
    libeconf
    libedit
    libei
    libepoxy
    liberation-mono-fonts
    libertas-firmware
    libestr
    libev
    libevdev
    libevent
    libexif
    libfastjson
    libfdisk
    libffi
    libfido2
    libfontenc
    libfprint
    libfsverity
    libftdi
    libgcc
    libgcrypt
    libgee
    libgexiv2
    libglvnd
    libglvnd-egl
    libglvnd-gles
    libglvnd-glx
    libglvnd-opengl
    libgomp
    libgpg-error
    libgphoto2
    libgs
    libgsf
    libguestfs-tools
    libgudev
    libgusb
    libgxps
    libhandy
    libhangul
    libheif
    libibverbs
    libical
    libICE
    libicu
    libidn2
    libiec61883
    libieee1284
    libijs
    libimagequant
    libimobiledevice
    libimobiledevice-glue
    libini_config
    libinput
    libipt
    libiptcdata
    libjaylink
    libjcat
    libjpeg-turbo
    libjxl
    libkcapi
    libkcapi-hasher
    libkcapi-hmaccalc
    libksba
    liblc3
    libldac
    libldb
    liblerc
    liblouis
    liblouis-tables
    liblouisutdml
    liblouisutdml-utils
    liblqr-1
    liblxqt
    libmanette
    libmaxminddb
    libmbim
    libmbim-utils
    libmnl
    libmodplug
    libmodulemd
    libmount
    libmpc
    libmpeg2
    libmspack
    libmysofa
    libndp
    libnetfilter_conntrack
    libnfnetlink
    libnfsidmap
    libnftnl
    libnghttp2
    libnice
    libnl3
    libnl3-cli
    libnma
    libnma-gtk4
    libnotify
    libnsl2
    libnvme
    liboeffis
    libogg
    libopenjph
    libopenmpt
    libosinfo
    libpaper
    libpasswdqc
    libpath_utils
    libpcap
    libpciaccess
    libpinyin
    libpinyin-data
    libpipeline
    libpkgconf
    libplacebo
    libplist
    libpng
    libpostproc-free
    libppd
    libproxy
    libpskc
    libpsl
    libpwquality
    libqmi
    libqmi-utils
    libqrtr-glib
    libqtxdg
    librabbitmq
    libraqm
    LibRaw
    libraw1394
    libref_array
    librepo
    libreport
    libreport-anaconda
    libreport-cli
    libreport-fedora
    libreport-filesystem
    libreport-gtk
    libreport-plugin-bugzilla
    libreport-plugin-kerneloops
    libreport-plugin-logger
    libreport-plugin-reportuploader
    libreport-plugin-systemd-journal
    libreport-plugin-ureport
    libreport-web
    libreswan
    librist
    librsvg2
    libsamplerate
    libsane-airscan
    libsane-hpaio
    libsbc
    libscfg
    libseccomp
    libsecret
    libselinux
    libselinux-utils
    libsemanage
    libsepol
    libshaderc
    libshout
    libsigc++20
    libsigc++30
    libSM
    libsmartcols
    libsmbclient
    libsndfile
    libsodium
    libsolv
    libsoup3
    libsrtp
    libss
    libssh
    libssh-config
    libsss_certmap
    libsss_idmap
    libsss_nss_idmap
    libsss_sudo
    libstdc++
    libstemmer
    libswresample-free
    libswscale-free
    libtalloc
    libtasn1
    libtdb
    libteam
    libtevent
    libtextstyle
    libthai
    libtheora
    libtiff
    libtinysparql
    libtirpc
    libtomcrypt
    libtommath
    libtool-ltdl
    libudfread
    libudisks2
    libunibreak
    libunistring
    libunwind
    liburing
    libusb1
    libusbmuxd
    libutempter
    libuuid
    libuv
    libv4l
    libva
    libva-intel-media-driver
    libvarlink
    libvdpau
    libverto
    libverto-libev
    libvisual
    libvmaf
    libvorbis
    libvpl
    libvpx
    libwacom
    libwacom-data
    libwayland-client
    libwayland-cursor
    libwayland-egl
    libwayland-server
    libwbclient
    libwebp
    libwmf-lite
    libwnck3
    libX11
    libX11-common
    libX11-xcb
    libXau
    libxcb
    libXcomposite
    libxcrypt
    libXcursor
    libxcvt
    libXdamage
    libXdmcp
    libXext
    libxfce4ui
    libxfce4util
    libxfce4windowing
    libXfixes
    libXfont2
    libXft
    libXi
    libXinerama
    libxkbcommon
    libxkbcommon-x11
    libxkbfile
    libxml2
    libxmlb
    libXmu
    libXpm
    libXpresent
    libXrandr
    libXrender
    libXres
    libXScrnSaver
    libxshmfence
    libxslt
    libXt
    libXtst
    libXv
    libXxf86vm
    libyaml
    libyuv
    libzip
    libzstd
    lilv-libs
    linux-atm-libs
    linux-firmware
    linux-firmware-whence
    livesys-scripts
    llvm-filesystem
    llvm-libs
    lm_sensors
    lm_sensors-libs
    localsearch
    lockdev
    logrotate
    low-memory-monitor
    lpcnetfreedv
    lrzsz
    lsof
    lttng-ust
    lua-libs
    lvm2
    lvm2-dbusd
    lvm2-libs
    lxqt-policykit
    lz4-libs
    lzo
    m17n-db
    m17n-lib
    mactel-boot
    madan-fonts
    mailcap
    makedumpfile
    malcontent-libs
    man-db
    man-pages
    mbedtls
    mcelog
    mdadm
    mediawriter
    memstrack
    mesa-dri-drivers
    mesa-filesystem
    mesa-libEGL
    mesa-libgbm
    mesa-libGL
    mesa-libGLU
    mesa-va-drivers
    mesa-vulkan-drivers
    microcode_ctl
    minicom
    miracle-wm
    miracle-wm-config
    mir-common-libs
    mir-lomiri-libs
    mir-server-libs
    mkpasswd
    mobile-broadband-provider-info
    ModemManager
    ModemManager-glib
    mokutil
    mozilla-filesystem
    mpage
    mpdecimal
    mpfr
    mpg123-libs
    mpv-libs
    mt7xxx-firmware
    mtdev
    mtools
    mtr
    mujs
    nano
    nano-default-editor
    ncurses
    ncurses-base
    ncurses-libs
    ndctl
    ndctl-libs
    nebula
    net-snmp-libs
    nettle
    net-tools
    NetworkManager
    NetworkManager-adsl
    network-manager-applet
    NetworkManager-bluetooth
    NetworkManager-l2tp
    NetworkManager-l2tp-gnome
    NetworkManager-libnm
    NetworkManager-libreswan
    NetworkManager-libreswan-gnome
    NetworkManager-openconnect
    NetworkManager-openconnect-gnome
    NetworkManager-openvpn
    NetworkManager-openvpn-gnome
    NetworkManager-ppp
    NetworkManager-pptp
    NetworkManager-pptp-gnome
    NetworkManager-sstp
    NetworkManager-sstp-gnome
    NetworkManager-team
    NetworkManager-vpnc
    NetworkManager-vpnc-gnome
    NetworkManager-wifi
    NetworkManager-wwan
    newt
    nfs-utils
    nftables
    nilfs-utils
    nmap
    nmap-ncat
    nm-connection-editor
    noopenh264
    npth
    nspr
    nss
    nss-mdns
    nss-softokn
    nss-softokn-freebl
    nss-sysinit
    nss-tools
    nss-util
    ntfs-3g
    ntfs-3g-libs
    ntfs-3g-system-compression
    ntfsprogs
    numactl-libs
    nvidia-gpu-firmware
    nvme-cli
    nvtop
    nwg-bar
    nwg-dock
    nwg-drawer
    nwg-panel
    nxpwireless-firmware
    oniguruma
    openal-soft
    OpenCL-ICD-Loader
    openconnect
    opencore-amr
    openexr-libs
    openjpeg
    openldap
    openpace
    openpgm
    open-sans-fonts
    opensc
    opensc-libs
    openssh
    openssh-clients
    openssh-server
    openssl-libs
    open-vm-tools
    open-vm-tools-desktop
    openvpn
    opus
    orc
    osinfo-db
    osinfo-db-tools
    os-prober
    ostree-libs
    p11-kit
    p11-kit-trust
    p7zip-plugins
    PackageKit
    PackageKit-glib
    PackageKit-gstreamer-plugin
    paktype-naskh-basic-fonts
    pam
    pam-libs
    pam_passwdqc
    pango
    pangomm
    pangomm2.48
    papirus-icon-theme
    papirus-icon-theme-dark
    papirus-icon-theme-light
    paps
    parted
    passim
    passim-libs
    passwdqc
    passwdqc-utils
    pavucontrol
    pcaudiolib
    pciutils
    pciutils-libs
    pcre2
    pcre2-syntax
    pcre2-utf16
    pcsc-lite
    pcsc-lite-ccid
    pcsc-lite-libs
    pigz
    pinentry
    pinentry-gnome3
    pinfo
    pipewire
    pipewire-alsa
    pipewire-gstreamer
    pipewire-jack-audio-connection-kit
    pipewire-jack-audio-connection-kit-libs
    pipewire-libs
    pipewire-plugin-libcamera
    pipewire-pulse
    pipewire-pulseaudio
    pipewire-utils
    pixman
    pkcs11-helper
    pkcs11-provider
    pkgconf
    pkgconf-m4
    pkgconf-pkg-config
    playerctl
    playerctl-libs
    plocate
    plymouth
    plymouth-core-libs
    plymouth-graphics-libs
    plymouth-plugin-label
    plymouth-plugin-two-step
    plymouth-scripts
    plymouth-system-theme
    plymouth-theme-spinner
    podman-compose
    policycoreutils
    policycoreutils-python-utils
    polkit
    polkit-libs
    polkit-pkla-compat
    polkit-qt6-1
    poppler
    poppler-cpp
    poppler-data
    poppler-glib
    poppler-utils
    popt
    powertop
    ppp
    pptp
    prefixdevname
    procps-ng
    protobuf-c
    psacct
    psmisc
    publicsuffix-list-dafsa
    pulseaudio-libs
    pulseaudio-libs-glib2
    pulseaudio-utils
    python3
    python3-abrt
    python3-abrt-addon
    python3-argcomplete
    python3-audit
    python3-augeas
    python3-beautifulsoup4
    python3-blivet
    python3-blockdev
    python3-boto3
    python3-botocore
    python3-brotli
    python3-bytesize
    python3-cairo
    python3-certifi
    python3-cffi
    python3-charset-normalizer
    python3-crypt-r
    python3-cups
    python3-dasbus
    python3-dateutil
    python3-dbus
    python3-dbus-next
    python3-distro
    python3-dnf
    python3-dnf-plugins-core
    python3-enchant
    python3-file-magic
    python3-firewall
    python3-gobject
    python3-gobject-base
    python3-hawkey
    python3-humanize
    python3-i3ipc
    python3-idna
    python3-iso639
    python3-jmespath
    python3-kickstart
    python3-langtable
    python3-libcomps
    python3-libdnf
    python3-libmount
    python3-libreport
    python3-libs
    python3-libselinux
    python3-libsemanage
    python3-libxml2
    python3-lxml
    python3-meh
    python3-meh-gui
    python3-mutagen
    python3-netifaces
    python3-newt
    python3-nftables
    python3-olefile
    python3-packaging
    python3-pexpect
    python3-pid
    python3-pillow
    python3-ply
    python3-policycoreutils
    python3-productmd
    python3-psutil
    python3-ptyprocess
    python3-pwquality
    python3-pyatspi
    python3-pycparser
    python3-pycryptodomex
    python3-pyparted
    python3-pysocks
    python3-pyudev
    python3-pyxdg
    python3-pyyaml
    python3-regex
    python3-requests
    python3-requests-file
    python3-requests-ftp
    python3-rpm
    python3-s3transfer
    python3-satyr
    python3-setools
    python3-setuptools
    python3-simpleaudio
    python3-simpleline
    python3-six
    python3-soupsieve
    python3-speechd
    python3-systemd
    python3-typing-extensions
    python3-unbound
    python3-urllib3
    python3-urllib3+socks
    python3-websockets
    python3-xkbregistry
    python3-xlib
    python-pip-wheel
    python-unversioned-command
    qemu-guest-agent
    qpdf-libs
    qrencode-libs
    qt5-qtgraphicaleffects
    qt6-filesystem
    qt6-qtbase
    qt6-qtbase-common
    qt6-qtbase-gui
    qt6-qtdeclarative
    qt6-qtsvg
    qt6-qttranslations
    qt6-qtwayland
    quota
    quota-nls
    rav1e-libs
    readline
    realmd
    realtek-firmware
    ripgrear
    rit-meera-new-fonts
    rit-rachana-fonts
    rootfiles
    rpcbind
    rpm
    rpm-build-libs
    rpm-libs
    rpm-plugin-audit
    rpm-plugin-selinux
    rpm-plugin-systemd-inhibit
    rpm-sequoia
    rpm-sign-libs
    rsvg-pixbuf-loader
    rsync
    rsyslog
    rtkit
    rubberband-libs
    samba-client
    samba-client-libs
    samba-common
    samba-common-libs
    sane-airscan
    sane-backends
    sane-backends-drivers-cameras
    sane-backends-drivers-scanners
    sane-backends-libs
    satyr
    sdbus-cpp
    sddm
    sddm-wayland-miraclewm
    sdl2-compat
    SDL3
    sed
    selinux-policy
    selinux-policy-targeted
    serd
    setroubleshoot
    setroubleshoot-plugins
    setroubleshoot-server
    setup
    setxkbmap
    shadow-utils
    shared-mime-info
    shim-ia32
    shim-x64
    sil-padauk-fonts
    skopeo
    slang
    slurp
    smartmontools
    smartmontools-selinux
    snappy
    sord
    sos
    sound-theme-freedesktop
    soundtouch
    source-highlight
    soxr
    speech-dispatcher
    speech-dispatcher-espeak-ng
    speech-dispatcher-libs
    speech-dispatcher-utils
    speex
    spice-vdagent
    spice-webdavd
    spirv-tools-libs
    sqlite-libs
    squashfs-tools
    sratom
    srt-libs
    sssd-client
    sssd-common
    sssd-kcm
    sssd-krb5-common
    sssd-nfs-idmap
    sssd-proxy
    sstp-client
    startup-notification
    steam-devices
    stix-fonts
    stoken-libs
    sudo
    sudo-python-plugin
    svt-av1-libs
    swaybg
    swayidle
    swaylock
    SwayNotificationCenter
    SwayNotificationCenter-bash-completion
    switcheroo-control
    symlinks
    syslinux
    system-config-language
    system-config-printer
    system-config-printer-libs
    system-config-printer-udev
    systemd
    systemd-libs
    systemd-networkd
    systemd-oomd-defaults
    systemd-pam
    systemd-resolved
    systemd-shared
    systemd-sysusers
    systemd-udev
    taglib
    tailscale
    tar
    tcl
    tcpdump
    teamd
    tecla
    tesseract-libs
    Thunar
    thunar-archive-plugin
    time
    tinysparql
    tiwilink-firmware
    tmux
    totem-pl-parser
    tpm2-tools
    tpm2-tss
    tpm2-tss-fapi
    traceroute
    tree
    tslib
    tumbler
    turbojpeg
    twolame-libs
    tzdata
    uchardet
    udftools
    udiskie
    udisks2
    udisks2-btrfs
    udisks2-iscsi
    unbound-anchor
    unbound-libs
    unicode-ucd
    unzip
    upower
    upower-libs
    urw-base35-bookman-fonts
    urw-base35-c059-fonts
    urw-base35-d050000l-fonts
    urw-base35-fonts
    urw-base35-fonts-common
    urw-base35-gothic-fonts
    urw-base35-nimbus-mono-ps-fonts
    urw-base35-nimbus-roman-fonts
    urw-base35-nimbus-sans-fonts
    urw-base35-p052-fonts
    urw-base35-standard-symbols-ps-fonts
    urw-base35-z003-fonts
    usb_modeswitch
    usb_modeswitch-data
    usbmuxd
    usbutils
    userspace-rcu
    utf8proc
    util-linux
    util-linux-core
    vapoursynth-libs
    vazirmatn-vf-fonts
    vid.stab
    vim-data
    vim-minimal
    virt-manager
    virtualbox-guest-additions
    vo-amrwbenc
    volume_key-libs
    vpnc
    vpnc-script
    vulkan-loader
    wavpack
    webkit2gtk4.1
    webp-pixbuf-loader
    webrtc-audio-processing
    wev
    wget2
    wget2-libs
    wget2-wget
    which
    whois
    whois-nls
    wireless-regdb
    wireguard-tools
    wireplumber
    wireplumber-libs
    wl-clipboard
    wlr-randr
    wlsunset
    woff2
    words
    wpa_supplicant
    wsdd
    xarchiver
    xcb-util
    xcb-util-cursor
    xcb-util-image
    xcb-util-keysyms
    xcb-util-renderutil
    xcb-util-wm
    xdg-dbus-proxy
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-wlr
    xdg-user-dirs
    xdg-utils
    xdriinfo
    xfce4-panel
    xfconf
    xfsprogs
    xhost
    xkbcomp
    xkeyboard-config
    xl2tpd
    xml-common
    xmlrpc-c
    xmlrpc-c-client
    xmlsec1
    xmlsec1-openssl
    xmodmap
    xorg-x11-server-Xwayland
    xorg-x11-xauth
    xorg-x11-xinit
    xprop
    xrdb
    xvidcore
    xxhash-libs
    xz
    xz-libs
    yaml-cpp
    yt-dlp
    yt-dlp-bash-completion
    yt-dlp+default
    zchunk-libs
    zenity
    zeromq
    zimg
    zip
    zix
    zlib-ng-compat
    zram-generator
    zram-generator-defaults
    zvbi
    
    # SoltrOS Additions
    fish
    zsh
    gimp
    deja-dup
    buildah
    fd-find
    git-delta
    btop
    gamemode
    gamemode-devel
    mangohud
    goverlay
    corectrl
    mbpfan
    thermald
    libvirtd
)

dnf5 install --setopt=install_weak_deps=False --allowerasing --nogpgcheck -y "${LAYERED_PACKAGES[@]}"

# Enabling various services
log "Enabling services"
systemctl enable pipewire.service || true
systemctl enable pipewire-pulse.service || true
systemctl enable wireplumber.service || true

# Remove Firefox to replace with Waterfox
log "Removing Firefox in favor of Waterfox"
dnf5 remove -y firefox firefox-* || true

log "Package installation complete"