name: Build SoltrOS LTS ISO

on:
  workflow_dispatch:
  push:
    branches: [ soltros-os-lts ]
    paths:
      - ".github/workflows/build-lts-iso.yml"

env:
  ARCH: x86_64
  IMAGE_NAME: soltros-os_lts
  IMAGE_REPO: ghcr.io/soltros
  IMAGE_TAG: latest

jobs:
  build_iso:
    name: Build Alma LTS ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: soltros-os-lts

      - name: Compute image ref
        shell: bash
        run: |
          echo "IMAGE_REF=${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}" >> "$GITHUB_ENV"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y podman skopeo jq qemu-utils xorriso

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show bootc-related labels (sanity)
        shell: bash
        run: |
          echo "Inspecting labels on ${IMAGE_REF}"
          skopeo inspect "docker://${IMAGE_REF}" | jq -r '.Labels'

      - name: Verify image is bootc+bootable
        shell: bash
        run: |
          BOOTC=$(skopeo inspect "docker://${IMAGE_REF}" | jq -r '.Labels["containers.bootc"] // ""')
          BOOTABLE=$(skopeo inspect "docker://${IMAGE_REF}" | jq -r '.Labels["ostree.bootable"] // ""')
          echo "containers.bootc=${BOOTC}"
          echo "ostree.bootable=${BOOTABLE}"
          if [[ "$BOOTC" != "1" || "$BOOTABLE" != "1" ]]; then
            echo "Image is missing required labels. Ensure Dockerfile has:"
            echo '  LABEL containers.bootc="1" ostree.bootable="1"'
            exit 1
          fi

      - name: Build ISO with bootc-image-builder
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p out cache
          podman pull ghcr.io/containers/bootc-image-builder:latest
          podman run --rm --privileged             -v /var/lib/containers:/var/lib/containers             -v "$PWD/out":/out             -v "$PWD/cache":/var/cache/bootc-image-builder             ghcr.io/containers/bootc-image-builder:latest             --type iso             --target-arch "${ARCH}"             --image "${IMAGE_REF}"

      - name: List outputs
        shell: bash
        run: ls -l out

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v5
        with:
          name: soltros-os-lts-iso
          path: out/*.iso
          if-no-files-found: error
