name: Build SoltrOS LTS Installer ISO (Alma)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Container tag to install (e.g. latest, latest.YYYYMMDD)"
        default: "latest"
        required: true
  push:
    branches:
      - soltros-os-lts
    paths:
      - ".github/workflows/build-lts-installer-iso.yml"

concurrency:
  group: lts-iso-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write          # needed if you enable the Release step
  packages: read
  id-token: write

env:
  IMAGE_REPO: ghcr.io/soltros/soltros-os_lts
  ARCH: x86_64

jobs:
  build_iso:
    name: Build bootc ISO
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo (for versioning/files if needed)
        uses: actions/checkout@v4

      - name: Maximize disk space
        uses: ublue-os/remove-unwanted-software@v7
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true

      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Podman CLI (host)
        run: |
          sudo apt-get update
          sudo apt-get install -y podman jq

      - name: Prepare container storage (btrfs on loopback)
        # This gives us faster builds and avoids overlayfs inode limits
        uses: ublue-os/container-storage-action@main

      - name: Resolve image and output names
        id: names
        shell: bash
        run: |
          TAG="${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || 'latest' }}"
          IMAGE="${IMAGE_REPO}:${TAG}"
          DATE=$(date -u +%Y%m%d)
          ISO_BASENAME="soltros-os-lts-alma-${TAG}-${DATE}-${ARCH}"
          echo "IMAGE=${IMAGE}"           | tee -a "$GITHUB_OUTPUT"
          echo "ISO_BASENAME=${ISO_BASENAME}" | tee -a "$GITHUB_OUTPUT"

      - name: Sanity check: image is bootc/bootable
        shell: bash
        run: |
          skopeo inspect "docker://${{ steps.names.outputs.IMAGE }}" | jq -r '.Labels' > labels.json
          echo "Labels:"
          cat labels.json | jq .
          want1=$(jq -r '."containers.bootc"' labels.json)
          want2=$(jq -r '."ostree.bootable"' labels.json)
          if [[ "${want1}" != "1" || "${want2}" != "1" ]]; then
            echo "::error title=Image not bootable::containers.bootc=${want1}, ostree.bootable=${want2}. Make sure you set both labels in the image."
            exit 1
          fi

      - name: Build bootable installer ISO with bootc-image-builder
        # bootc-image-builder itself runs in a privileged container
        shell: bash
        run: |
          mkdir -p out
          podman pull quay.io/centos-bootc/bootc-image-builder:latest
          podman run --rm --privileged \
            -v "$PWD/out":/out \
            -v /var/lib/containers:/var/lib/containers:Z \
            quay.io/centos-bootc/bootc-image-builder:latest \
              --type bootiso \
              --output-filename "${{ steps.names.outputs.ISO_BASENAME }}" \
              --image "${{ steps.names.outputs.IMAGE }}"

          ls -lh out/

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.names.outputs.ISO_BASENAME }}
          path: out/${{ steps.names.outputs.ISO_BASENAME }}.iso
          if-no-files-found: error
          compression-level: 0   # keep it fast; ISO is already compressed

      # --- Optional: publish a Release with the ISO attached ---
      # Uncomment this job step if you want a Release automatically.
      # - name: Create GitHub Release (optional)
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: lts-installer-${{ steps.names.outputs.ISO_BASENAME }}
      #     name: "SoltrOS LTS Alma installer – ${{ steps.names.outputs.ISO_BASENAME }}"
      #     generate_release_notes: true
      #     files: |
      #       out/${{ steps.names.outputs.ISO_BASENAME }}.iso
