name: Build and Push SoltrOS Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the container image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
