name: Build and Push SoltrOS Image
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go for crane
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install crane
        run: |
          go install github.com/google/go-containerregistry/cmd/crane@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/soltros-os:latest
          no-cache: true

      - name: Sign and attest
        # Only run if the cosign private key exists
        if: ${{ secrets.COSIGN_PRIVATE_KEY != '' }}
        run: |
          DIGEST=$(crane digest ghcr.io/${{ github.repository_owner }}/soltros-os:latest)
          
          # Sign image
          cosign sign \
            --yes \
            --key env://COSIGN_PRIVATE_KEY \
            --tlog-upload=true \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Create and sign SBOM attestation
        # Only run if the cosign private key exists
        if: ${{ secrets.COSIGN_PRIVATE_KEY != '' }}
        run: |
          DIGEST=$(crane digest ghcr.io/${{ github.repository_owner }}/soltros-os:latest)
          
          # Create a proper SBOM predicate
          cat <<EOF > sbom.json
          {
            "predicateType": "https://spdx.dev/Document",
            "predicate": {
              "spdxVersion": "SPDX-2.3",
              "dataLicense": "CC0-1.0",
              "SPDXID": "SPDXRef-DOCUMENT",
              "name": "SoltrOS Image SBOM",
              "documentNamespace": "https://github.com/${{ github.repository }}/sbom-${{ github.run_id }}",
              "creationInfo": {
                "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
                "creators": ["Tool: GitHub Actions"]
              },
              "packages": [
                {
                  "SPDXID": "SPDXRef-Package",
                  "name": "soltros-os",
                  "downloadLocation": "NOASSERTION",
                  "filesAnalyzed": false,
                  "copyrightText": "NOASSERTION"
                }
              ]
            }
          }
          EOF

          # Attach SBOM
          cosign attest \
            --yes \
            --key env://COSIGN_PRIVATE_KEY \
            --predicate sbom.json \
            --type spdx \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}