name: Build and Push SoltrOS Image
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Keys
        run: |
          curl -sL https://raw.githubusercontent.com/soltros/Soltros-OS/main/soltros.pub > repo-key.pub
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > secret-key.pub
          if ! diff -u repo-key.pub secret-key.pub; then
            echo "::error::Key mismatch between repo and GitHub secret!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/soltros-os:latest
            ghcr.io/${{ github.repository_owner }}/soltros-os:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
          no-cache: true
      - name: Install crane
        run: |
            # Install go-containerregistry tools
            go install github.com/google/go-containerregistry/cmd/crane@latest
            echo "$(go env GOPATH)/bin" >> $GITHUB_PATH    
            
      - name: Sign with Cosign
        run: |
          # Sign with digest to avoid tag warnings
          DIGEST=$(crane digest ghcr.io/${{ github.repository_owner }}/soltros-os:latest)
          cosign sign \
            --yes \
            --key env://COSIGN_PRIVATE_KEY \
            --upload=true \
            --tlog-upload=true \
            --recursive \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST

          # Create SBOM attestation (modern syntax)
          cosign attest \
            --yes \
            --key env://COSIGN_PRIVATE_KEY \
            --type spdx \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Verify Deployment
        run: |
          DIGEST=$(crane digest ghcr.io/${{ github.repository_owner }}/soltros-os:latest)
          
          # Verify signature
          cosign verify \
            --key <(echo "${{ secrets.COSIGN_PUBLIC_KEY }}") \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST

          # Verify SBOM
          cosign verify-attestation \
            --key <(echo "${{ secrets.COSIGN_PUBLIC_KEY }}") \
            --type spdx \
            ghcr.io/${{ github.repository_owner }}/soltros-os@$DIGEST